# Generated by Django 5.2.6 on 2026-04-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_predictionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='stock_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='stock_name',
            field=models.CharField(max_length=50),
        ),
    ]
